# Generated by Django 3.2.16 on 2023-03-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='other_quantity',
            new_name='order_quantity',
        ),
    ]
